version: '3.8'

services:
  db:
    image: postgres:14.18
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: combatintel
    ports:
      - "5435:5432"
    volumes:
      - combatintel_db:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    env_file:
      - .env

volumes:
  combatintel_db:
